<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="1" failures="0" skip="0"><testcase classname="test" name="test_loading" time="0.000"><error type="exceptions.IOError" message="[Errno 2] No such file or directory: 'salinasA.json'"><![CDATA[Traceback (most recent call last):
  File "/Users/xehivs/anaconda2/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/xehivs/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/xehivs/dev/hssa/tests/test.py", line 25, in test_loading
    hs = loadImage()
  File "/Users/xehivs/dev/hssa/tests/test.py", line 17, in loadImage
    with open('salinasA.json') as data_file:
IOError: [Errno 2] No such file or directory: 'salinasA.json'
]]></error></testcase></testsuite>